#!/usr/bin/python

"""Amulet tests on a basic ceilometer deployment on precise-icehouse."""

from basic_deployment import CeilometerBasicDeployment

if __name__ == '__main__':
    deployment = CeilometerBasicDeployment(series='precise',
                                           openstack='cloud:precise-icehouse',
                                           source='cloud:precise-updates/icehouse')
    deployment.run_tests()
