#!/usr/bin/python

"""Amulet tests on a basic ceilometer deployment on trusty-juno."""

from basic_deployment import CeilometerBasicDeployment

if __name__ == '__main__':
    deployment = CeilometerBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-juno',
                                           source='cloud:trusty-updates/juno')
    deployment.run_tests()
