#!/usr/bin/python

"""Amulet tests on a basic ceilometer deployment on trusty-liberty."""

from basic_deployment import CeilometerBasicDeployment

if __name__ == '__main__':
    deployment = CeilometerBasicDeployment(series='trusty',
                                           openstack='cloud:trusty-liberty',
                                           source='cloud:trusty-updates/liberty')
    deployment.run_tests()
