#!/usr/bin/python

"""Amulet tests on a basic ceilometer deployment on wily-liberty."""

from basic_deployment import CeilometerBasicDeployment

if __name__ == '__main__':
    deployment = CeilometerBasicDeployment(series='wily')
    deployment.run_tests()
