#!/bin/bash

# This script sets up the requirements for amulet tests.

set -x 

# Check if amulet is installed before adding the stable repository and updating apt-get.
dpkg -s amulet
if [ $? -ne 0 ]; then
    sudo add-apt-repository -y ppa:juju/stable
    sudo apt-get update -qq
    sudo apt-get install -y amulet
fi

# Install any additional python packages or other required software.
sudo apt-get install -y python3-requests