#!/usr/bin/python

import setup
setup.pre_install()

from charmhelpers.core import hookenv
from charmhelpers.fetch import apt_upgrade, apt_install


def install():
    hookenv.log('Installing keepalived')

    apt_upgrade(fatal=True, dist=True)
    apt_install('keepalived', fatal=True)


if __name__ == "__main__":
    install()
